version: "3"
services:
  elasticsearch:
    image: elasticsearch:8.6.2
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elastic-vol:/usr/share/elasticsearch/data
    networks:
      - main-net
    ports:
      - 9200:9200

  kibana:
    image: kibana:8.6.2
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - main-net
    ports:
      - 5601:5601

volumes:
  elastic-vol:
    driver: local

networks:
  main-net:
    driver: bridge
